@startuml
start
:Участник выбирает мероприятие;
:Авторизация в системе;
:Проверка свободных мест;
if (Есть свободные места?) then (да)
    :Заполнение формы регистрации;
    :Отправка заявки;
    :Система регистрирует запись;
    stop
else (нет)
    :Показ сообщения "Свободных мест нет";
    stop
endif
@enduml
